In [ ]:
#supervised learning, predictive model, response variable, target variable

#when the response variable is categorical, the model is called classification tree.

#random forest is based on decision tree

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from pandas import Series, DataFrame

In [2]:
loans = pd.read_csv("lending_club_data01.csv")

In [3]:
loans.head()

int_rate  installment  open_acc  revol_bal  revol_util  total_acc  \
0     10.65       162.87         3      13648        83.7          9   
1     15.27        59.83         3       1687         9.4          4   
2     15.96        84.33         2       2956        98.5         10   
3     13.49       339.31        10       5598        21.0         37   
4      7.90       156.46         9       7963        28.3         12   

   bad_loans  grade_num  
0          0          5  
1          1          4  
2          0          4  
3          0          4  
4          0          6

In [9]:
numerical_features = [feature for feature in loans.columns if loans[feature].dtypes != 'O']

print('Number of numerical variables: ', len(numerical_features))

# visualise the numerical variables
loans[numerical_features].head()

Number of numerical variables:  8


INT_RATE  INSTALLMENT  OPEN_ACC  REVOL_BAL  REVOL_UTIL  TOTAL_ACC  \
0     10.65       162.87         3      13648        83.7          9   
1     15.27        59.83         3       1687         9.4          4   
2     15.96        84.33         2       2956        98.5         10   
3     13.49       339.31        10       5598        21.0         37   
4      7.90       156.46         9       7963        28.3         12   

   BAD_LOANS  GRADE_NUM  
0          0          5  
1          1          4  
2          0          4  
3          0          4  
4          0          6

In [10]:
loans.columns = map(str.upper, loans.columns)

In [11]:
loans.head()

INT_RATE  INSTALLMENT  OPEN_ACC  REVOL_BAL  REVOL_UTIL  TOTAL_ACC  \
0     10.65       162.87         3      13648        83.7          9   
1     15.27        59.83         3       1687         9.4          4   
2     15.96        84.33         2       2956        98.5         10   
3     13.49       339.31        10       5598        21.0         37   
4      7.90       156.46         9       7963        28.3         12   

   BAD_LOANS  GRADE_NUM  
0          0          5  
1          1          4  
2          0          4  
3          0          4  
4          0          6

In [12]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468 entries, 0 to 1467
Data columns (total 8 columns):
INT_RATE       1468 non-null float64
INSTALLMENT    1468 non-null float64
OPEN_ACC       1468 non-null int64
REVOL_BAL      1468 non-null int64
REVOL_UTIL     1468 non-null float64
TOTAL_ACC      1468 non-null int64
BAD_LOANS      1468 non-null int64
GRADE_NUM      1468 non-null int64
dtypes: float64(3), int64(5)
memory usage: 91.8 KB


In [9]:
loans.isnull().sum()

INT_RATE       0
INSTALLMENT    0
OPEN_ACC       0
REVOL_BAL      0
REVOL_UTIL     0
TOTAL_ACC      0
BAD_LOANS      0
GRADE_NUM      0
dtype: int64

In [13]:
loans.tail(10)

INT_RATE  INSTALLMENT  OPEN_ACC  REVOL_BAL  REVOL_UTIL  TOTAL_ACC  \
1458     13.49       118.76        17      22059        83.1         40   
1459     19.03       325.46        25       7016        39.4         36   
1460     11.71        76.08         7       2166        36.7          8   
1461     10.65       223.13         7       2173        58.7         14   
1462      7.90       187.75        22       9050        22.3         44   
1463      6.62       377.66        11      10825        16.1         25   
1464     18.64       360.41         2        564        70.5         19   
1465     16.29       494.21        15      24536        71.7         29   
1466      7.90       500.65         4        404        31.1         12   
1467     15.27       208.79         6        760        69.1         19   

      BAD_LOANS  GRADE_NUM  
1458          0          4  
1459          0          2  
1460          0          5  
1461          1          5  
1462          0          6  
1463          0          6  
1464          0          2  
1465          0          3  
1466          0          6  
1467          0          4

In [13]:
#create a new columns, good_loans, bad_loans=0 and good_loans=1, use lambda function

In [19]:
loans['good_loans'] = loans['BAD_LOANS'].apply(lambda y: 'yes' if y== 0 else 'no')

In [20]:
loans.head(5)

INT_RATE  INSTALLMENT  OPEN_ACC  REVOL_BAL  REVOL_UTIL  TOTAL_ACC  \
0     10.65       162.87         3      13648        83.7          9   
1     15.27        59.83         3       1687         9.4          4   
2     15.96        84.33         2       2956        98.5         10   
3     13.49       339.31        10       5598        21.0         37   
4      7.90       156.46         9       7963        28.3         12   

   BAD_LOANS  GRADE_NUM good_loans  
0          0          5        yes  
1          1          4         no  
2          0          4        yes  
3          0          4        yes  
4          0          6        yes

In [21]:
#now we are selecting the features expect the good loans and the bad loans and includes it in the target 

In [38]:
X= loans.drop(['BAD_LOANS', 'good_loans'], axis =1)

In [39]:
y= loans['good_loans']

In [55]:
print(X.shape, y.shape)

(1468, 7) (1468,)


# use train_test to split and use decison training 
 

In [27]:
from sklearn.model_selection import train_test_split 

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state= 124)
                                                   

In [57]:
print(X_train.shape, X_test.shape)

(1027, 7) (441, 7)


In [58]:
print(y_train.shape, y_test.shape)

(1027,) (441,)


In [59]:
model= DecisionTreeClassifier()

In [60]:
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [67]:
prediction = model.predict(X_test)

In [68]:
from sklearn.metrics import classification_report, confusion_matrix

In [70]:
print (confusion_matrix(y_test, prediction))

[[ 14  53]
 [ 70 304]]


In [72]:
print (classification_report (y_test, prediction))

              precision    recall  f1-score   support

          no       0.17      0.21      0.19        67
         yes       0.85      0.81      0.83       374

   micro avg       0.72      0.72      0.72       441
   macro avg       0.51      0.51      0.51       441
weighted avg       0.75      0.72      0.73       441



In [73]:
#random forest classifier model

In [77]:
from sklearn.ensemble.forest import RandomForestClassifier

In [82]:
rf_model =RandomForestClassifier(n_estimators =150)

In [83]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [84]:
rf_prediction = rf_model.predict(X_test)

In [87]:
print(classification_report(y_test, rf_prediction))

              precision    recall  f1-score   support

          no       0.44      0.10      0.17        67
         yes       0.86      0.98      0.91       374

   micro avg       0.84      0.84      0.84       441
   macro avg       0.65      0.54      0.54       441
weighted avg       0.79      0.84      0.80       441



In [88]:
print(confusion_matrix(y_test, rf_prediction))

[[  7  60]
 [  9 365]]


# LETS CONSIDER A LARGER DATASET

In [90]:
loans = pd.read_csv('lending_club_new_data.csv')

In [91]:
loans.head(6)

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   
5       3000         3000             3000     18.64       109.43       48000   

     dti  delinq_2yrs  inq_last_6mths  open_acc        ...          \
0  27.65            0               1         3        ...           
1   1.00            0               5         3        ...           
2   8.72            0               2         2        ...           
3  20.00            0               1        10        ...           
4  11.20            0               3         9        ...           
5   5.35            0               2         4        ...           

   total_rec_late_fee  recoveries  collection_recovery_fee  last_pymnt_amnt  \
0                0.00        0.00                     0.00           171.62   
1                0.00      117.08                     1.11           119.66   
2                0.00        0.00                     0.00           649.91   
3               16.97        0.00                     0.00           357.48   
4                0.00        0.00                     0.00           161.03   
5                0.00        0.00                     0.00           111.34   

   bad_loans  emp_length_num  grade_num  sub_grade_num  delinq_2yrs_zero  \
0          0              11          5            0.4                 1   
1          1               1          4            0.8                 1   
2          0              11          4            1.0                 1   
3          0              11          4            0.2                 1   
4          0               4          6            0.8                 1   
5          0              10          2            0.2                 1   

   payment_inc_ratio  
0            8.14350  
1            2.39320  
2            8.25955  
3            8.27585  
4            5.21533  
5            2.73575  

[6 rows x 24 columns]

In [92]:
loans.shape

(9516, 24)

In [93]:
loans.tail()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  \
9511       6000         6000             6000     23.40       170.53   
9512      15250        15250            15250     17.57       548.05   
9513       8525         8525             8525     18.25       217.65   
9514      22000        22000            22000     19.97       582.50   
9515       2000         2000             2000      7.90        62.59   

      annual_inc    dti  delinq_2yrs  inq_last_6mths  open_acc  \
9511       45600   1.50            1               0         3   
9512       65000  11.26            1               2         8   
9513       37536  12.28            4               0        12   
9514       78000  18.45            0               5        18   
9515       83000   5.39            3               1        21   

            ...          total_rec_late_fee  recoveries  \
9511        ...                         0.0         0.0   
9512        ...                         0.0         0.0   
9513        ...                         0.0      1159.4   
9514        ...                         0.0         0.0   
9515        ...                         0.0         0.0   

      collection_recovery_fee  last_pymnt_amnt  bad_loans  emp_length_num  \
9511                    0.000           170.53          1               0   
9512                    0.000         14810.30          0              11   
9513                   11.594           217.65          1               6   
9514                    0.000            17.50          1              11   
9515                    0.000          1500.68          0               4   

      grade_num  sub_grade_num  delinq_2yrs_zero  payment_inc_ratio  
9511          2            1.0                 0           4.487630  
9512          3            0.4                 0          10.117800  
9513          3            0.6                 0           6.958120  
9514          3            1.0                 1           8.961540  
9515          6            0.8                 0           0.904916  

[5 rows x 24 columns]

In [94]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9516 entries, 0 to 9515
Data columns (total 24 columns):
loan_amnt                  9516 non-null int64
funded_amnt                9516 non-null int64
funded_amnt_inv            9516 non-null int64
int_rate                   9516 non-null float64
installment                9516 non-null float64
annual_inc                 9516 non-null int64
dti                        9516 non-null float64
delinq_2yrs                9516 non-null int64
inq_last_6mths             9516 non-null int64
open_acc                   9516 non-null int64
total_pymnt                9516 non-null float64
total_pymnt_inv            9516 non-null float64
total_rec_prncp            9516 non-null float64
total_rec_int              9516 non-null float64
total_rec_late_fee         9516 non-null float64
recoveries                 9516 non-null float64
collection_recovery_fee    9516 non-null float64
last_pymnt_amnt            9516 non-null float64
bad_loans                

In [95]:
loans.isnull().sum()

loan_amnt                  0
funded_amnt                0
funded_amnt_inv            0
int_rate                   0
installment                0
annual_inc                 0
dti                        0
delinq_2yrs                0
inq_last_6mths             0
open_acc                   0
total_pymnt                0
total_pymnt_inv            0
total_rec_prncp            0
total_rec_int              0
total_rec_late_fee         0
recoveries                 0
collection_recovery_fee    0
last_pymnt_amnt            0
bad_loans                  0
emp_length_num             0
grade_num                  0
sub_grade_num              0
delinq_2yrs_zero           0
payment_inc_ratio          0
dtype: int64

In [96]:
loans['good_loans']= loans['bad_loans'].apply(lambda y: 'yes' if y==0 else 'no')

In [97]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc     ...      recoveries  \
0  27.65            0               1         3     ...            0.00   
1   1.00            0               5         3     ...          117.08   
2   8.72            0               2         2     ...            0.00   
3  20.00            0               1        10     ...            0.00   
4  11.20            0               3         9     ...            0.00   

   collection_recovery_fee  last_pymnt_amnt  bad_loans  emp_length_num  \
0                     0.00           171.62          0              11   
1                     1.11           119.66          1               1   
2                     0.00           649.91          0              11   
3                     0.00           357.48          0              11   
4                     0.00           161.03          0               4   

   grade_num  sub_grade_num  delinq_2yrs_zero  payment_inc_ratio  good_loans  
0          5            0.4                 1            8.14350         yes  
1          4            0.8                 1            2.39320          no  
2          4            1.0                 1            8.25955         yes  
3          4            0.2                 1            8.27585         yes  
4          6            0.8                 1            5.21533         yes  

[5 rows x 25 columns]

In [98]:
X= loans.drop(['bad_loans', 'good_loans'], axis =1 )

In [99]:
y=loans['good_loans']

In [100]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.3, random_state= 124)

In [103]:
print(X_train.shape, y_test.shape)

(6661, 23) (2855,)


In [104]:
model2= DecisionTreeClassifier()

In [105]:
model2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [106]:
prediction2 = model2.predict(X_test)

In [107]:
print(confusion_matrix(y_test, prediction2))

[[ 444   11]
 [   8 2392]]


In [108]:
print(classification_report(y_test, prediction2))

              precision    recall  f1-score   support

          no       0.98      0.98      0.98       455
         yes       1.00      1.00      1.00      2400

   micro avg       0.99      0.99      0.99      2855
   macro avg       0.99      0.99      0.99      2855
weighted avg       0.99      0.99      0.99      2855



In [ ]:
#random forest classifier model

In [110]:
rf_model2 =RandomForestClassifier(n_estimators =150)

In [111]:
rf_model2.fit(X_train,y_train)  

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [117]:
rf_prediction2 = rf_model2.predict(X_test)

In [124]:
print(confusion_matrix(y_test, rf_prediction))

[[ 443   12]
 [   0 2400]]


In [123]:
print(confusion_matrix(y_test, rf_prediction2))

[[ 443   12]
 [   0 2400]]


In [121]:
print(classification_report(y_test, rf_prediction2))

              precision    recall  f1-score   support

          no       1.00      0.97      0.99       455
         yes       1.00      1.00      1.00      2400

   micro avg       1.00      1.00      1.00      2855
   macro avg       1.00      0.99      0.99      2855
weighted avg       1.00      1.00      1.00      2855



In [122]:
print(classification_report(y_test, rf_prediction))

              precision    recall  f1-score   support

          no       1.00      0.97      0.99       455
         yes       1.00      1.00      1.00      2400

   micro avg       1.00      1.00      1.00      2855
   macro avg       1.00      0.99      0.99      2855
weighted avg       1.00      1.00      1.00      2855

