In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [5]:
X = iris.data
y= iris.target

In [7]:
print (X.shape)

(150, 4)


In [8]:
print(y.shape)

(150,)


In [9]:
#lets create a dataframe to reporesent the iris dataset

In [11]:
iris = pd.DataFrame(X, columns= iris.feature_names)

In [12]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [13]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [14]:
#lets do text analysis

In [15]:
train_text = ['go home tonight', 'go take a cab', 'soccer! go play soccer...']

In [16]:
#step1 = convert the text into a numerical format
#step2 = for the algorithm to work the texts has to be on some length

#step 3 = we use count vectorizer

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
vector = CountVectorizer()

In [19]:
vector.fit(train_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [20]:
vector.get_feature_names()

['cab', 'go', 'home', 'play', 'soccer', 'take', 'tonight']

In [21]:
train_text

['go home tonight', 'go take a cab', 'soccer! go play soccer...']

In [22]:
train_text_dtmatrix = vector.transform(train_text)

In [23]:
train_text_dtmatrix

<3x7 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [24]:
# 7= number of columns
#3 = number of rows, each row represent a single string in text

In [25]:
#convert to array

In [26]:
train_text_dtmatrix.toarray()

array([[0, 1, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 2, 0, 0]], dtype=int64)

In [28]:
text = pd.DataFrame(train_text_dtmatrix.toarray(), columns= vector.get_feature_names())

In [30]:
text.head()

cab  go  home  play  soccer  take  tonight
0    0   1     1     0       0     0        1
1    1   1     0     0       0     1        0
2    0   1     0     1       2     0        0

In [31]:
#text feature extraction

In [32]:
train_text

['go home tonight', 'go take a cab', 'soccer! go play soccer...']

In [33]:
type(train_text)

list

In [34]:
type(train_text_dtmatrix)

scipy.sparse.csr.csr_matrix

In [36]:
print (train_text_dtmatrix)

  (0, 1)	1
  (0, 2)	1
  (0, 6)	1
  (1, 0)	1
  (1, 1)	1
  (1, 5)	1
  (2, 1)	1
  (2, 3)	1
  (2, 4)	2


In [37]:
test_text = ['soccer dont play go']

In [38]:
test_text_dmatrix = vector.transform(test_text)  #converted into a documental matrix

In [39]:
test_text_dmatrix.toarray()  #to array

array([[0, 1, 0, 1, 1, 0, 0]], dtype=int64)

In [40]:
pd.DataFrame(test_text_dmatrix.toarray(), columns= vector.get_feature_names())

cab  go  home  play  soccer  take  tonight
0    0   1     0     1       1     0        0

In [43]:
test_text= ["soccer dont play just go home",\
            "hey, i hope to see you all in the soccer games",\
            "the game was awesome, he scored at the end and won", \
            "the game was awesome,he scored at the end, won and off to home"]
           

In [44]:
test_text

['soccer dont play just go home',
 'hey, i hope to see you all in the soccer games',
 'the game was awesome, he scored at the end and won',
 'the game was awesome,he scored at the end, won and off to home']

In [45]:
test_text_dmatrix = vector.transform(test_text)

In [46]:
test_text_dmatrix.toarray() 

array([[0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [47]:
pd.DataFrame(test_text_dmatrix.toarray(), columns= vector.get_feature_names())

cab  go  home  play  soccer  take  tonight
0    0   1     1     1       1     0        0
1    0   0     0     0       1     0        0
2    0   0     0     0       0     0        0
3    0   0     1     0       0     0        0

In [ ]:
#we are considering a data set ham and spam, analyze the data, convert into documental matrix, build a model, and evaluate the model.

In [49]:
sms_messages = pd.read_csv("SMSSpamCollection", sep='\t', names=['label', 'message'])

In [51]:
sms_messages.head() #ham means not spam

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
# or uses this function----------sms_messages = pd.read_table('sms_data.tsv', header = None, names= ['label', 'message'])

In [55]:
sms_messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [58]:
sms_messages.describe()

label                 message
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [62]:
sms_messages.shape


(5572, 2)

In [64]:
#how many spama and ham

sms_messages.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [65]:

#create new feature/column label_number

sms_messages['label_number'] = sms_messages.label.map({'ham': 0, 'spam': 1})

In [66]:
sms_messages.head()

label                                            message  label_number
0   ham  Go until jurong point, crazy.. Available only ...             0
1   ham                      Ok lar... Joking wif u oni...             0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...             1
3   ham  U dun say so early hor... U c already then say...             0
4   ham  Nah I don't think he goes to usf, he lives aro...             0

In [67]:
X = sms_messages.message

In [68]:
y= sms_messages.label_number

In [69]:
print(X.shape)

(5572,)


In [70]:
print(y.shape)

(5572,)


In [71]:
#train and test dataset

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.3, random_state = 15)

In [74]:
print(X_train.shape, X_test.shape)

(3900,) (1672,)


In [75]:
print(y_train.shape, y_test.shape)

(3900,) (1672,)


# countvectorizer , create dtm object and build our model

In [76]:
vector = CountVectorizer()

In [77]:
vector.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [78]:
X_train_dtmatrix = vector.transform(X_train)

In [79]:
print(X_train_dtmatrix.shape)

(3900, 7259)


In [80]:
X_train_dtmatrix

<3900x7259 sparse matrix of type '<class 'numpy.int64'>'
	with 52431 stored elements in Compressed Sparse Row format>

In [81]:
X_test_dtmatrix = vector.transform(X_test)

In [82]:
X_test_dtmatrix

<1672x7259 sparse matrix of type '<class 'numpy.int64'>'
	with 20111 stored elements in Compressed Sparse Row format>

In [83]:
print(X_test.shape)

(1672,)


In [84]:
from sklearn.naive_bayes import MultinomialNB

In [85]:
nb_model = MultinomialNB()

In [86]:
nb_model.fit(X_train_dtmatrix, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [88]:
y_prediction = nb_model.predict(X_test_dtmatrix)

In [90]:
from sklearn import metrics

In [91]:
metrics.accuracy_score(y_test, y_prediction)

0.986244019138756

In [92]:
print(metrics.confusion_matrix(y_test, y_prediction)) #TN FP FN TP

[[1443    5]
 [  18  206]]


# LOGISTIC REGRESSSION MODEL

In [94]:
from sklearn.linear_model import LogisticRegression

In [95]:
log_model = LogisticRegression()

In [96]:
log_model.fit(X_train_dtmatrix, y_train)

C:\Users\NIBIN JOSEPH\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [97]:
y_prediction2 = log_model.predict(X_test_dtmatrix)

In [98]:
print(metrics.accuracy_score(y_test, y_prediction2))

0.9820574162679426


In [99]:
print(metrics.accuracy_score(y_test, y_prediction))

0.986244019138756


In [100]:
print(metrics.confusion_matrix(y_test, y_prediction2))

[[1444    4]
 [  26  198]]


In [101]:
print(metrics.confusion_matrix(y_test, y_prediction))

[[1443    5]
 [  18  206]]


In [ ]:
y_test< y_prediction

In [ ]:
#0<1

In [103]:
X_test[y_test < y_prediction]

1082                    Can u get pic msgs to your phone?
45                       No calls..messages..missed calls
991                                          26th OF JULY
5475    Dhoni have luck to win some big title.so we wi...
1506    Total video converter free download type this ...
Name: message, dtype: object

In [104]:
X_test[y_test > y_prediction]

672     SMS. ac sun0819 posts HELLO:"You seem cool, wa...
3742                                        2/2 146tf150p
4144    In The Simpsons Movie released in July 2007 na...
5037    You won't believe it but it's true. It's Incre...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
4213    Missed call alert. These numbers called but le...
227     Will u meet ur dream partner soon? Is ur caree...
2770    Burger King - Wanna play footy at a top stadiu...
4676    Hi babe its Chloe, how r u? I was smashed on s...
3574    You won't believe it but it's true. It's Incre...
1269    Can U get 2 phone NOW? I wanna chat 2 set up m...
1458    CLAIRE here am havin borin time & am now alone...
4069    TBS/PERSOLVO. been chasing us since Sept for£3...
2575    Your next amazing xxx PICSFREE1 video will be ...
1638    0A$NETWORKS allow companies to bill for SMS, s...
731     Email AlertFrom: Jeri StewartSize: 2KBSubject:...
788     Ever t

In [105]:
len(X_test[y_test > y_prediction])

18

In [106]:
X_test[731]

'Email AlertFrom: Jeri StewartSize: 2KBSubject: Low-cost prescripiton drvgsTo listen to email call 123'

In [107]:
len(X_test[y_test > y_prediction2])

26

# lets find out the most common spam and ham words

In [108]:
X_train_words = vector.get_feature_names()

In [109]:
len(X_train_words)

7259

In [110]:
X_train_words[:5]

['00', '000', '008704050406', '0089', '01223585236']

In [112]:
X_train_words[7000:7010]

['were',
 'werethe',
 'wesley',
 'west',
 'westlife',
 'westonzoyland',
 'westshore',
 'wet',
 'wetherspoons',
 'what']

In [113]:
#feature count method

In [117]:
nb_model.feature_count_

array([[ 0.,  0.,  0., ...,  1.,  0.,  1.],
       [ 6., 21.,  2., ...,  0.,  1.,  0.]])

In [118]:
nb_model.feature_count_.shape

(2, 7259)

In [120]:
ham_word_count= nb_model.feature_count_[0:1]

In [121]:
spam_word_count= nb_model.feature_count_[1:]

In [131]:
ham_word_count.shape

(1, 7259)

In [132]:
spam_word_count

array([[ 6., 21.,  2., ...,  0.,  1.,  0.]])

In [133]:
tokens =  pd.DataFrame({'token' : X_train_words,'ham': ham_word_count, 'spam':spam_word_count})

Exception: Data must be 1-dimensional

In [128]:
tokens.head()

NameError: name 'tokens' is not defined

In [134]:
nb_model.class_count_

array([3377.,  523.])